services:
  cryptostream:
    build:
      context: .
      dockerfile: ./docker/crypto-stream/Dockerfile

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    network_mode: host
    user: root
    volumes:
      - ./docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - cryptostream
    command: ["--strict.perms=false"]
